LAB_1_2 : main_lab_2.o fun_g.o fun_f.o
	gcc main_lab_2.o fun_g.o fun_f.o -o LAB_1_2

main_lab_2.o : main_lab_2.c
	gcc -c main_lab_2.c -o main_lab_2.o

fun_g.o : fun_g.c
	gcc -c fun_g.c -o fun_g.o

fun_f.o : fun_f.c
	gcc -c fun_f.c -o fun_f.o
